Dim fso
   Set fso = CreateObject("Scripting.FileSystemObject")
   Dim fullpath
   fullpath = fso.GetAbsolutePathName(".")
   Set fso = Nothing

Set objExcel = Wscript.CreateObject("Excel.Application")   
Set objWorkbook = objExcel.Workbooks.Open(fullpath & "\datasheet.xlsx")   
objExcel.visible=True
rowCount=objExcel.ActiveWorkbook.Sheets(1).UsedRange.Rows.count
colCount=objExcel.ActiveWorkbook.Sheets(1).UsedRange.Columns.count  
Redim row(rowCount, colCount)
for intRow=2 to rowCount  step 1
    if (CStr(objExcel.Cells(intRow, 1).Value) <> "") then      
      for intCol=1 to colCount step 1  
        c = objExcel.Cells(intRow, intCol).Value
        row(intRow, intCol) = c
      next
      
    End if
        c=null
        
    text ="<?xml version='1.0' encoding='utf-8' ?>"
    text = text & vbNewLine & "<configuration>"
    text = text & vbNewLine & "    <configSections>"
    text = text & vbNewLine & "        <sectionGroup name='userSettings' type='System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' >"
    text = text & vbNewLine & "            <section name='HappyPath.Properties.Settings' type='System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' allowExeDefinition='MachineToLocalUser' requirePermission='false' />"
    text = text & vbNewLine & "        </sectionGroup>"
    text = text & vbNewLine & "    </configSections>"
    text = text & vbNewLine & "    <startup>"
    text = text & vbNewLine & "       <supportedRuntime version='v4.0' sku='.NETFramework,Version=v4.6.1' />"
    text = text & vbNewLine & "    </startup>" 
    text = text & vbNewLine & "    <userSettings>"
    text = text & vbNewLine & "        <HappyPath.Properties.Settings>"
    text = text & vbNewLine & "            <setting name='appUrl' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 1) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='userName' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 2) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "             <setting name='password' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 3) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "             <setting name='pTitle' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 4) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pFname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 5) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pLname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 6) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pGender' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 7) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pDay' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 8) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pMonth' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 9) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbnewLine & "            <setting name='pYear' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 10) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbnewLine & "            <setting name='pSmokingOption' serializeAs='String'>"
    text = text & vbnewLine & "                <value>" & row(intRow, 11) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='height' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 12) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='weight' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 13) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='waist' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 14) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='postcode' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 15) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='occupation' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 16) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pSalary' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 17) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pLifeCover' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 18) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pLifeYears' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 19) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pLifePeriod' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 20) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pLifeIncreasing' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 21) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pLifeAmt' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 22) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pCiCover' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 23) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pCiPeriod' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 24) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pCiYears' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 25) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pCiIncreasing' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 26) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pCiAmt' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 27) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sTitle' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 28) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sFname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 29) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sLname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 30) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sGender' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 31) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sDay' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 32) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sMonth' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 33) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sYear' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 34) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sSalary' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 35) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sLifeCover' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 36) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sLifeYears' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 37) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sLifePeriod' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 38) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sLifeIncreasing' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 39) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sLifeAmt' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 40) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sCiCover' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 41) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sCiPeriod' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 42) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sCiYears' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 43) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sCiIncreasing' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 44) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sCiAmt' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 45) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sSmokingOption' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 46) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='mortgageChoice' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 47) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='cCiAmt' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 48) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='cFname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 49) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='cLname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 50) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='cDay' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 51) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='cMonth' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 52) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='cYear' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 53) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pEmail' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 54) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pPhoneNum' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 55) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pAddLineOne' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 56) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pAddLineTwo' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 57) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pAddTown' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 58) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pAddCounty' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 59) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pAddPostcode' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 60) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sEmail' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 61) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sPhoneNum' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 62) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sAddLineOne' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 63) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sAddLineTwo' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 64) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sAddTown' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 65) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sAddCounty' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 66) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sAddPostcode' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 67) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBeneficiary' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 68) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBenFname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 69) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBenLname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 70) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBenDay' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 71) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBenMonth' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 72) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBenYear' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 73) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='pBenPercent' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 74) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBeneficiary' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 75) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBenFname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 76) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBenLname' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 77) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBenDay' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 78) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBenMonth' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 79) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBenYear' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 80) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='sBenPercent' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 81) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='commStyle' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 82) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "            <setting name='commSacrifice' serializeAs='String'>"
    text = text & vbNewLine & "                <value>" & row(intRow, 83) & "</value>"
    text = text & vbNewLine & "            </setting>"
    text = text & vbNewLine & "        </HappyPath.Properties.Settings>"
    text = text & vbNewLine & "    </userSettings>"
    text = text & vbNewLine & "</configuration>"    

    set xmlDoc=CreateObject("Microsoft.XMLDOM")
    xmlDoc.async=false
    xmlDoc.loadXML(text)
    xmlDoc.Save fullpath & "\Happy Path Automator" & intRow & ".exe.config"
Next